name: flutterfire_sample_app_check
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+2
environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.7.1
  firebase_app_check: ^0.1.4+1
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/.env
